name: Publish to Azure
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: shortalink-webapp    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './out'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
    - uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - run: dotnet restore
    - run: dotnet publish -c Release -o /out --no-restore
    - name: 'Deploy to Azure WebApp'
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
